language: python
python:
  - 3.6
services:
  - docker
stages:
  - name: docker_push
    if: branch = master
before_install:
  - pip install docker-compose
install:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  - docker-compose pull || true
  - docker-compose build
jobs:
  include:
    - stage: docker_push
      script:
        - docker-compose push
git:
  submodules: false
